name: Keep Render Server Alive

on:
  schedule:
    # Runs every 7 minutes
    - cron: '*/7 * * * *'
  workflow_dispatch: # Allows manual testing

jobs:
  ping_site:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the URL
        run: |
          curl -I https://smart-home-solar-system-backend.onrender.com
